Update nokogiri dependency
1.8.5 fails hard `rake` locally with:

    rm config/application.rb
    bin/rake app:template LOCATION='../../example_app_generator/generate_stuff.rb'
    rake aborted!
    LoadError: dlopen(/Users/pirj/source/rspec-dev/repos/bundle/ruby/2.5.0/gems/nokogiri-1.8.5/lib/nokogiri/nokogiri.bundle, 9): Library not loaded: /Users/pirj/.rvm/rubies/ruby-2.5.3/lib/libruby.2.5.dylib
      Referenced from: /Users/pirj/source/rspec-dev/repos/bundle/ruby/2.5.0/gems/nokogiri-1.8.5/lib/nokogiri/nokogiri.bundle
      Reason: image not found - /Users/pirj/source/rspec-dev/repos/bundle/ruby/2.5.0/gems/nokogiri-1.8.5/lib/nokogiri/nokogiri.bundle
    /Users/pirj/source/rspec-dev/repos/bundle/ruby/2.5.0/gems/nokogiri-1.8.5/lib/nokogiri.rb:32:in `require'
    ...

    Caused by:
    LoadError: cannot load such file -- nokogiri/2.5/nokogiri
    /Users/pirj/source/rspec-dev/repos/bundle/ruby/2.5.0/gems/nokogiri-1.8.5/lib/nokogiri.rb:30:in `require'
    /Users/pirj/source/rspec-dev/repos/bundle/ruby/2.5.0/gems/nokogiri-1.8.5/lib/nokogiri.rb:30:in `<top (required)>'
    /Users/pirj/source/rspec-dev/repos/bundle/ruby/2.5.0/gems/loofah-2.4.0/lib/loofah.rb:4:in `require'

1.9.1 supports Ruby 2.1+.