Remove the integration_tool hook in ScaffoldsController
Fixes the problem that ScaffoldsGenerator creates the separate request specs
through the IntegrationGenerator class.

Naming of example resources in generate_stuff task is changed
because I suspect that using the integration generator before scaffolding (with the same name) produced the following error

```
     NameError:
       undefined local variable or method `widgets_index_path' for #<RSpec::ExampleGroups::Widgets::GETWidgets:0x00007f881832e338>
     # ./spec/requests/widgets_spec.rb:6:in `block (3 levels) in <top (required)>'
```

Since this kind of usage does not make sense anyway
I changed the used scaffolding name to product